devices:
  - !reservoir
    label: reservoir1
    volume: 1000
    fluid: !water {}
  - !valve
    label: valve1
    state: 'open'
  - !pump
    label: pump1
    state: 'on'
  - !valve
    label: valve2
    state: 'open'
  - !tank
    label: tank1

connections:
  reservoir1:
    outputs: 
     - valve1
  valve1:
    outputs:
     - pump1
  pump1:
    outputs:
     - valve2
  valve2:
    outputs:
     - tank1
