settings:
  speed: 1

devices:
  - !reservoir
    label: reservoir1
    volume: 1000
    fluid: !water {}
  - !valve
    label: valve1
    state: 'open'
  - !pump
    label: pump1
    state: 'on'
  - !filter
    label: filter1
  - !valve
    label: valve2
    state: 'open'
  - !pump
    label: pump2
    state: 'on'
  - !tank
    label: chlorinetank
    volume: 100
    fluid: !chlorine {}
  - !valve
    label: chlorinevalve
    state: 'closed'
  - !pump
    label: chlorinepump
    state: 'on'
  - !tank
    label: chlorinator
  - !pump
    label: pump3
    state: 'on'
  - !valve
    label: valve3
    state: 'open'
  - !tank
    label: municipaltank

connections:
  reservoir1:
    outputs: 
     - valve1
  valve1:
    outputs:
     - pump1
  pump1:
    outputs:
     - filter1
  filter1:
    outputs:
     - valve2
  valve2:
    outputs:
     - pump2
  pump2:
    outputs:
     - chlorinator
  chlorinetank:
    outputs:
     - chlorinevalve
  chlorinevalve:
    outputs:
     - chlorinepump
  chlorinepump:
    outputs:
     - chlorinator
  chlorinator:
    outputs:
     - valve3
  valve3:
    outputs:
     - pump3
  pump3:
    outputs:
     - municipaltank

sensors:
  - !volume
    label: reservoirsensor
    connected_to: reservoir1
  - !volume
    label: chlorinetanksensor
    connected_to: chlorinetank
  - !volume
    label: chlorinatorsensor
    connected_to: chlorinator
  - !volume
    label: municipaltanksensor
    connected_to: municipaltank
  - !state
    label: valve1sensor
    connected_to: valve1
  - !state
    label: chlorinevalvesensor
    connected_to: chlorinevalve
  - !state
    label: valve2sensor
    connected_to: valve2
  - !state
    label: valve3sensor
    connected_to: valve3
  - !state
    label: pump1sensor
    connected_to: pump1
  - !state
    label: pump2sensor
    connected_to: pump2
  - !state
    label: pump3sensor
    connected_to: pump3
  - !state
    label: chlorinepumpsensor
    connected_to: chlorinepump

/*
  slaveid

      Each slave in a network is assigned a unique unit address from 1 to 247. When the master requests data, 
      the first byte it sends is the Slave address. This way each slave knows after the first byte 
      whether or not to ignore the message.

  data_offset & data_address

    Coil/Register Numbers   Data Addresses  Type        Table Name                          Use
    1-9999                  0000 to 270E    Read-Write  Discrete Output Coils               on/off read/write
    10001-19999             0000 to 270E    Read-Only   Discrete Input Contacts             on/off readonly
    30001-39999             0000 to 270E    Read-Only   Analog Input Registers              analog readonly
    40001-49999             0000 to 270E    Read-Write  Analog Output Holding Registers     analog read/write

*/
plcs:
  plc1:
    slaveid: 1                  # valid range: 1-247
    sensors:
      reservoirsensor:
          data_offset: 2001       # Valid values: 1, 1001, 2001, or 3001
          data_address: 0x0000    # Valid values: 0x0000 - 0x270e
      pump1sensor:
          data_offset: 1
          data_address: 0x0000
      valve1sensor:
          data_offset: 1
          data_address: 0x0001
  chlorinatorplc:
    slaveid: 2
    sensors:
      chlorinetanksensor:
          data_offset: 2001
          data_address: 0x0000
      chlorinevalvesensor:
          data_offset: 1
          data_address: 0x0000
      chlorinepumpsensor:
          data_offset: 1
          data_address: 0x0001
      chlorinatorsensor:
          data_offset: 2001
          data_address: 0x0001
  plc2:
    slaveid: 3
    sensors:
      valve2sensor:
          data_offset: 1
          data_address: 0x0000
      pump2sensor:
          data_offset: 1
          data_address: 0x0001
  plc3:
    slaveid: 4
    sensors:
      valve3sensor:
          data_offset: 1
          data_address: 0x0000
      pump3sensor:
          data_offset: 1
          data_address: 0x0001
      municipaltanksensor:
          data_offset: 2001
          data_address: 0x0000